### PR TITLE
throttled autosaveOnKeyup; #513

### PR DESCRIPTION
**Pull request by jfols**
It would be nice to add an option to set the throttle time, but I'm not sure where to pull that option from the way I'm creating the throttled autosave function.

### CODE REVIEW

**Comment by jfols** [comment]
I created the `autosaveOnKeyup` option to differentiate from the existing `autosave` option. It's quite likely that some applications will want the current behavior of `autosave` while others may want `autosaveOnKeyup`.

**Comment by aldeed** [comment]
In the `change form` event, I think it should also autosave when `autosaveOnKeyup` is `true`, as a safety. I recall issues in the past where keyup doesn't necessary have the final correct value, so best to save it on change, too.

Also can you change the two instances of the word "thrown" to "emitted" in the readme text?

Otherwise looks mergeable. Thanks for doing it.

**Comment by jfols** [comment]
Done and done :smile: No problem man, thanks for all you work on this package!

**Comment by jfols** [comment]
Should probably recommend `trimStrings=false` option in conjunction with `autosaveOnKeyup`, otherwise spaces may be deleted while typing.

**Comment by aldeed** [comment]
Good point re `trimStrings`. I'll add that to the readme.

**Pull request merged**
