### PR TITLE
bugfix: enable user to specify throttleTime for validateField function

### PR DESCRIPTION
**Pull request by Chun-Yang**
https://github.com/aldeed/meteor-autoform/issues/934

### CODE REVIEW

**Comment by Chun-Yang** [comment]
This code is not correct, I will fix it latter.

**Comment by Adiel-Sharabi** [comment]
1+, 
any news?

**Comment by devarashetty** [comment]
1+

**Comment by aldeed** [comment]
Closing this since it was never fixed. As written, it would not correctly throttle.

**Pull request closed without merging**
