### PR TITLE
Add autoform-datemask

### PR DESCRIPTION
**Pull request by jkutianski**

### CODE REVIEW

**Comment by jankapunkt** [comment]
Hi @jkutianski do you still maintain the datemask component? The last update was somewhere in 2019.

**Comment by jkutianski** [comment]
I was fired from my previous work (a gov institution) where I used Meteor. And at the moment I'm not involved on any Meteor based project.
Just 8 apps are using it and if anyone want a change I will review and add it. But no PR for changes so can't say that I mantaining  it.

**Comment by jankapunkt** [comment]
Hi @jkutianski still interested to see this merged? Do you still use / maintain this extension?

**Comment by jkutianski** [comment]
Yes I still interested.

**Comment by jankapunkt** [comment]
Ok I am planning to merge some of the PRs that are still Open but create no conflicts (Like yours) this Weekend.

**Pull request merged**
